-- SQL Script to Update Activity Fields in workplan_budget_items Table
-- Change from TINYINT (0-255) to SMALLINT UNSIGNED (0-65535)
-- This allows storing quantity values from 0 to 1000

-- Run this SQL directly in your database

ALTER TABLE `workplan_budget_items` 
MODIFY COLUMN `activity_jan` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_feb` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_mar` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_apr` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_may` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_jun` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_jul` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_aug` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_sep` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_oct` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_nov` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN `activity_dec` SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Verify the changes
DESCRIBE `workplan_budget_items`;
